<a href="https://colab.research.google.com/github/Pygum/Tensorflow_Learning_Path_Material/blob/main/00_Tensorflow_Introduction_Udemy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow
##簡單而言，TensorFlow就是將一堆線性代數的metrix玩弄於股掌之中

More Specially, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors (Good Start!)
* Tensors & Numpy
* Using @tf.function to speed up your regular Python functions (How?)
* Using GPUs with Tensorflow (or TPUs)
* Exercises to try your own projects

#Introduciton to Tensors

### Create a tensor with tf.Constant()

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__) #Double underscore

2.12.0


In [ ]:
# Create tensors with tf.constant() (Many times we won't import all tensor module by import tf only)
# 1. Create a number
scalar = tf.constant(7)
scalar
# we create an empty Tensorflow with 7 Numpy in Tensorflow are quite intertwined.
# Creates a constant tensor from a tensor-like object. -- shape=()
# https://www.tensorflow.org/api_docs/python/tf/constant

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# 2. Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of the above vector
vector.ndim

1

In [ ]:
# 3. Check a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the dimension of the above matrix
matrix.ndim
# Something like 一元二次方程的二次 (not that easy)

2

In [ ]:
# 4. Check a matrix (has more than 2 X 3 dimension)
matrix2 = tf.constant([[10,8,7],
                     [7,8,10]])
matrix2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  8,  7],
       [ 7,  8, 10]], dtype=int32)>

In [ ]:
# Again 2
matrix2.ndim

2

In [ ]:
# 5. Check another matrix
matrix3 = tf.constant([[10.,7.], #. dot means float
                     [7.,10.],
                     [8.,9.]],dtype=tf.float16) # constant(value,dtype,shape,name='Constnt')

matrix3

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Check the dimension of the above metrix
matrix3.ndim
# still 2

2

In [ ]:
# 6. Let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[3,4,5]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 4, 5]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimension array of numbers
* Tensors: an n dimensional array of numbers

### Creating tensors with `tf.Variables`

In [ ]:
# create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor
#tf.Variable
#https://www.tensorflow.org/api_docs/python/tf/Variable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try to change the unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Create a random tensor

In [ ]:
#tf.random的用法在一些deeplearning model裡面很常用,用於傳入神經層的時候 initialized 準備裝著tensors的容器，(更好地適應數據)
#shape好個tensor然後當有其他的數據進入就可以output機器看得懂的result data.
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility 再現性 create一個容器
random_1 = random_1.normal(shape=(3,2)) #賦值進這個容器，通過normalization的形式。還有uniform的形式，是常數的格式。
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))
#normal distribution N正態分
random_1,random_2,random_1 == random_2
#pseudo random!!!

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
tf.random.normal(shape=(3,2)) #沒有seed 每次都different results

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.5750322 , -0.862609  ],
       [-0.47167432,  1.1187593 ],
       [-1.458317  , -0.7771538 ]], dtype=float32)>

###Shuffle the order of elements in a tensor
#####Shuffle the data can help model learn randomly and learn more precise

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent orfer doesn't affect)
not_shuffle = tf.constant([[10,7],[3,4]])
not_shuffle.ndim

2

In [ ]:
#ShuffleShuffle our non_shuffle tensor
tf.random.shuffle(not_shuffle)
#shuffle function can randomly change the seed in the random function shown as above

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffle,seed=42) #will get the different results

tf.random.set_seed(42) #https://www.tensorflow.org/api_docs/python/tf/random/set_seed #global seed # get the same results
tf.random.shuffle(not_shuffle,seed=42) #this will make us the same order #operation level seed

# 關於set_Seed的一些規則
#### global seed 會適用於想要穩定的結果 ｜ operation level seed 會想要打亂的結果
It looks like if we want our shuffled tensors wo be in the same order, we've got to use the global level random seed as well as the operation level random seed:

> If both the global and operation level seed are set: Both seeds are used in conjunction to determine the random sequence.

用法：你可能想要實驗結果重現，就用同樣的順序，還可能想打亂順序，讓機器學習充分（<red>後者有猜的成分<red>）




In [ ]:
#沒有global and operation seed 每次都different results
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.00412071], shape=(1,), dtype=float32)
tf.Tensor([0.3780992], shape=(1,), dtype=float32)
tf.Tensor([0.6765541], shape=(1,), dtype=float32)
tf.Tensor([0.2962978], shape=(1,), dtype=float32)


In [ ]:
#只有global seed 沒有operation level seed
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  #每次都是一樣的results,只是按著順序取已經獲得的數
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)
tf.Tensor([0.59750986], shape=(1,), dtype=float32)


In [ ]:
#只有operation level seed 沒有global seed 每次都會變
print(tf.random.uniform([1], seed=1))
print(tf.random.uniform([1], seed=1)) #每次結果都不同
print(tf.random.uniform([1], seed=1))
print(tf.random.uniform([1], seed=1))

tf.Tensor([0.69941723], shape=(1,), dtype=float32)
tf.Tensor([0.7062043], shape=(1,), dtype=float32)
tf.Tensor([0.33758223], shape=(1,), dtype=float32)
tf.Tensor([0.03662574], shape=(1,), dtype=float32)


In [ ]:
#global and operation level seed都有 #會選擇聽global setting的先
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))
print(tf.random.uniform([1], seed=1))
#tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))
print(tf.random.uniform([1], seed=1))

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.4243431], shape=(1,), dtype=float32)
tf.Tensor([0.92531705], shape=(1,), dtype=float32)


#Other ways to Create Tensors
Numpy

In [ ]:
#create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create a tensor of all zeros
tf.zeros([10,7])
#tf.zeros(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors
The main difference between Numpy arrays and Tensorflow tensors is that
tensors can be run on a GPU computing.

In [ ]:
# you can also turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) #create an array between 1 and 25
numpy_A
#X = tf.constant(matrix)#大寫
#y = tf.constant(vector) #小寫

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A.ndim

1

In [ ]:
B = tf.constant(numpy_A,shape=(4,3,2))
B #tensor is one more than dimension

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [ ]:
B.ndim

3

#Getting information from tensors

When dealing with tensors you probably want to be aware of the follow attributes:
* Shape tf.shape
* Rank tf.ndim | tensor's dimension is n
* Axis or dimension tensor[0],tensor[:,1]...
* Size tf.size(tensor) | the total number of items in the tensor

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[1,3,1,2])
rank_4_tensor

<tf.Tensor: shape=(1, 3, 1, 2), dtype=float32, numpy=
array([[[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]]], dtype=float32)>

In [ ]:
#most of time we need to pass a tensor into a neural network with a certain shape, it's good to deduce the elements of a tensor in the shape at first.
rank_4_tensor[0]

<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[0., 0.]],

       [[0., 0.]],

       [[0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor) #numpy=6 means 6 elements

(TensorShape([1, 3, 1, 2]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [ ]:
# GetGet various attributes of the tensor
#因為有時候處理起來tensor超級大，不會想詳細看，所以需要用information來迅速掌握一些信息
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor[0])
print("Number of Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Number of Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor))
print("Total number of elements in our tensor:",tf.size(rank_4_tensor).numpy())#tensor size = 6 | numpy size =6

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (1, 3, 1, 2)
Elements along the 0 axis: tf.Tensor(
[[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]], shape=(3, 1, 2), dtype=float32)
Number of Elements along the 0 axis: 1
Number of Elements along the last axis: 2
Total number of elements in our tensor: tf.Tensor(6, shape=(), dtype=int32)
Total number of elements in our tensor: 6


### Indexing tensors for exact any element you want.
Tensors can be indexed just like Python lists.
* list=[1,2,3,4,5]
* list[:2]
* ->[1,2]

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:1,:2]

<tf.Tensor: shape=(1, 2, 1, 2), dtype=float32, numpy=
array([[[[0., 0.]],

        [[0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimsion from each index except for the final one
rank_4_tensor[:1,:1,:1] #without choosing the final dimension means get the whole thing
#rank_4_tensor[:1,:1,:1,:]
#rank_4_tensor[:1,:,:1,:]

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[0., 0.]]]], dtype=float32)>

In [ ]:
# Reshape the tensor
#Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim,tf.size(rank_2_tensor)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
#Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1] #✨ if we want to add an extra dimension onto this ship

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor to alter and line up size for neural network
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
#rank_3_tensor = rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor #add a new dimension
#https://www.tensorflow.org/api_docs/python/tf/Tensor | means None in numpy

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # "-1" means expand the final axis
#https://www.tensorflow.org/api_docs/python/tf/expand_dims

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0),rank_2_tensor

(<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
 array([[[10,  7],
         [ 3,  4]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

# Manipulatng Tensor (tensor operations like above shown)
Basic Operations
`+` `-` `*` `/`

In [ ]:
# You can add values to a tensor with the addition operator
tensor = tf.constant([[10,7],
                     [3,4]])
tensor + 10
tensor - 10
tensor * 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# You can also use the tensorflow built-in funstion too
tf.multiply(tensor,10)
tf.add(tensor,10)
#tf.sub(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

### Matrix multiplication
In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors/matrix need to fulfill if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions

In [ ]:
#http://matrixmultiplication.xyz multiplication illustration
tf.matmul(tensor,tensor)
#https://www.tensorflow.org/api_docs/python/tf/linalg/matmul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor
# Different result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# Matrix multiplicaiton with Python operator "@"
tensor @ tensor
#the same result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Creat a tensor (3,2)
X = tf.constant([[1,2],[2,3],[4,5]])
Y = tf.constant([[4,5],[5,6],[7,8]])
X * Y
tf.matmul(X,Y)
# Resources: https://www.mathsisfun.com/algebra/matrix-multiplying.html

InvalidArgumentError: ignored

In [ ]:
# Reshape Y
tf.reshape(Y,shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
# Try to multiply X by reshaped Y
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 19, 21],
       [26, 31, 34],
       [46, 55, 60]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 19, 21],
       [26, 31, 34],
       [46, 55, 60]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 33],
       [67, 79]], dtype=int32)>

In [ ]:
# Can do the same with transpose
tf.transpose(X).shape

TensorShape([2, 3])

In [ ]:
X,Y,tf.transpose(X),tf.reshape(X,shape=(2,3)) #reshape would shuffle the order

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 5],
        [5, 6],
        [7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 4],
        [2, 3, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 2],
        [3, 4, 5]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 49],
       [58, 68]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 5],
        [5, 6],
        [7, 8]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be reansposed)
tf.tensordot(tf.transpose(X),Y,axes=0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[ 4,  5],
         [ 5,  6],
         [ 7,  8]],

        [[ 8, 10],
         [10, 12],
         [14, 16]],

        [[16, 20],
         [20, 24],
         [28, 32]]],


       [[[ 8, 10],
         [10, 12],
         [14, 16]],

        [[12, 15],
         [15, 18],
         [21, 24]],

        [[20, 25],
         [25, 30],
         [35, 40]]]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 49],
       [58, 68]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(X),Y) # the difference between matmul and tensordot????

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 49],
       [58, 68]], dtype=int32)>

In [ ]:
# Perform matrix multiplicaiton
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 17, 23],
       [23, 28, 38],
       [41, 50, 68]], dtype=int32)>

In [ ]:
# Perform matrix multiplication
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 19, 21],
       [26, 31, 34],
       [46, 55, 60]], dtype=int32)>

* Use which type of transpose/reshape depends on your project
* Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tesors to get satisfy the matrix multiplicaiton rules.

In [ ]:
### Changing the datatype of tensors
B = tf.constant([[1.2,1.3],[4.5,4.3]])
B,B.dtype #default data type is float32

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.2, 1.3],
        [4.5, 4.3]], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([2,3])
C,C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
 tf.int32)

In [ ]:
# Change from 32 into 16 (reduced precision for faster operation time)
D = tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[1.2, 1.3],
        [4.5, 4.3]], dtype=float16)>,
 tf.float16)

#Aggregating tensors
Aggregating tensors  = condensing them from multiple values down to a smaller amount of values.

In [ ]:
# Get the absolute values
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation: (find the mean of tensonr in tensorflow)
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of tensor
* Do some research


In [ ]:
# Create a ramdom tensor with values between 0 and 100 of size 50
import numpy as np
E = tf.constant(np.random.randint(0,100, size=50))
E,tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([42, 49, 29, 71,  5, 81, 81, 44, 73, 34, 36, 40, 46, 66, 26, 32, 71,
        49,  8, 32, 54,  0, 27, 81, 50, 75, 20, 78, 66, 65, 40, 15, 95, 26,
         1, 30, 16,  0, 58, 57, 13, 56, 38, 54, 30, 89, 32, 51, 63, 47])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]),
 1)

In [ ]:
# Find the minimum
tf.reduce_min(E) #最小值為2
#np.min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
np.min(E)

2

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2486>

***Exercise:*** With what we have just learned, find the variance and standard deviation of our `E` tensor using Tensorflow methods.

In [ ]:
# Find tensorflow variance and standard deviation 方差和標準差
# not work: tf.reduce_variance(E)
import tensorflow_probability as tfp #結合概率模型和深度學習
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=593>

In [ ]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=593.2544>

In [ ]:
# Find the standard deviation
tf.math.reduce_std(E)

TypeError: ignored

In [ ]:
# Cannot be int
tf.math.reduce_std(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=26.06>

###Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (Removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G,G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [ ]:
# 減少tensor中的單一維度來精簡tensor
G_squeezed = tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One-hot encoding tensors

In [ ]:
# Create a list of indices
lists= [0,2,3,5]
# One hot encode our list of indices
tf.one_hot(lists,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Specify custom value for one hot encoding ***
tf.one_hot(lists,depth=4,on_value='Hey Whats up guys',off_value='Nothing just dance')
#https://www.tensorflow.org/api_docs/python/tf/one_hot

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Hey Whats up guys', b'Nothing just dance',
        b'Nothing just dance', b'Nothing just dance'],
       [b'Nothing just dance', b'Nothing just dance',
        b'Hey Whats up guys', b'Nothing just dance'],
       [b'Nothing just dance', b'Nothing just dance',
        b'Nothing just dance', b'Hey Whats up guys'],
       [b'Nothing just dance', b'Nothing just dance',
        b'Nothing just dance', b'Nothing just dance']], dtype=object)>

#### Come to more tf.math function
##### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root (will error, method require float)
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H,dtype=tf.float32))


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy
Tensorflow interacts beautifully with Numpy arrays.

In [ ]:
# Create a tensor directly from a Numpy
#import numpy as np
J = tf.constant(np.array([1,2,3,4,5]))
J

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

In [ ]:
# Convert our tensor back to a Numpy array
np.array(J),type(np.array(J))

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [ ]:
# Convert tensor J to a Numpy array # Another method
J.numpy(),type(J.numpy())

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [ ]:
J = tf.constant([3]) # 用處，方便取得某數
J.numpy()[0]

3

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3,4,5]))
tensor_J = tf.constant([3,4,5])
# Check the datatype of each
numpy_J.dtype, tensor_J.dtype #有不同的時態

(tf.int64, tf.int32)

## Finding access to GPUs
* GPU can do quick numeric computing
* TPU is an AI accelerator application-specific integrated circuit (ASIC)

In [ ]:
tf.config.list_physical_devices() #the programming is running in CPU

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[]

In [ ]:
# Runtime > Change runtime type > GPU/TPU
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
# check if the GPU fulfills the requirement
!nvidia-smi

Tue May  2 15:15:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> **Note:** If you have access to a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible.